# src/specir/lowering/assert_to_sva.py
#
# Lowers a unified AssertModule to Yosys-compatible SystemVerilog assertions.
# Uses procedural `assert` statements inside an `always @(posedge clk)` block
# so that SymbiYosys/Yosys can parse them without syntax errors.

import re
from typing import Dict, List, Optional, Set, Union

from specir.dialects import assert_ir
from specir.utils.expr import parse_sexpr, ExprError
from specir.utils.logger import get_logger

logger = get_logger(__name__)


def _sva_expr(expr: Union[str, List, int, bool]) -> str:
    """
    Convert a parsed S‑expression (or raw string) into a SystemVerilog
    Boolean expression suitable for use inside an `assert(...)`.
    """
    if isinstance(expr, str):
        try:
            expr = parse_sexpr(expr)
        except ExprError:
            return expr

    if isinstance(expr, bool):
        return "1'b1" if expr else "1'b0"
    if isinstance(expr, int):
        return str(expr)

    if not isinstance(expr, list) or len(expr) == 0:
        return str(expr)

    op = expr[0]
    args = expr[1:]

    # Arithmetic
    if op in ('add', 'sub', 'mul', 'div', 'mod'):
        if len(args) != 2:
            raise ValueError(f"{op} expects 2 arguments")
        a = _sva_expr(args[0]); b = _sva_expr(args[1])
        sv_op = {'add': '+', 'sub': '-', 'mul': '*', 'div': '/', 'mod': '%'}[op]
        return f"({a} {sv_op} {b})"

    # Logical
    elif op == 'and':
        if len(args) != 2:
            raise ValueError("and expects 2 arguments")
        a = _sva_expr(args[0]); b = _sva_expr(args[1])
        return f"({a} && {b})"
    elif op == 'or':
        if len(args) != 2:
            raise ValueError("or expects 2 arguments")
        a = _sva_expr(args[0]); b = _sva_expr(args[1])
        return f"({a} || {b})"
    elif op == 'not':
        if len(args) != 1:
            raise ValueError("not expects 1 argument")
        a = _sva_expr(args[0])
        return f"!{a}"

    # Comparisons
    elif op in ('eq', 'neq', 'gt', 'lt', 'gte', 'lte', 'le', 'ge'):
        if len(args) != 2:
            raise ValueError(f"{op} expects 2 arguments")
        a = _sva_expr(args[0]); b = _sva_expr(args[1])
        sv_op = {'eq': '==', 'neq': '!=', 'gt': '>', 'lt': '<',
                 'gte': '>=', 'lte': '<=', 'le': '<=', 'ge': '>='}[op]
        return f"({a} {sv_op} {b})"

    # Implication – expands to (!a || b) because simple `assert` does not support `|->`
    elif op == 'implies':
        if len(args) != 2:
            raise ValueError("implies expects 2 arguments")
        a = _sva_expr(args[0]); b = _sva_expr(args[1])
        return f"(!{a} || {b})"

    # Concatenation / slicing
    elif op == 'concat':
        if len(args) != 2:
            raise ValueError("concat expects 2 arguments")
        a = _sva_expr(args[0]); b = _sva_expr(args[1])
        return f"{{{a}, {b}}}"
    elif op == 'slice':
        if len(args) != 3:
            raise ValueError("slice expects 3 arguments")
        e = _sva_expr(args[0])
        h = int(_sva_expr(args[1]))
        l = int(_sva_expr(args[2]))
        return f"{e}[{h}:{l}]"

    # if‑then‑else
    elif op == 'ite':
        if len(args) != 3:
            raise ValueError("ite expects 3 arguments")
        cond = _sva_expr(args[0])
        t = _sva_expr(args[1])
        e = _sva_expr(args[2])
        return f"({cond} ? {t} : {e})"

    # read a signal
    elif op == 'read':
        if len(args) != 1:
            raise ValueError("read expects 1 argument")
        name = args[0]
        if isinstance(name, str):
            return name
        raise ValueError("read argument must be a signal name string")

    else:
        raise ValueError(f"Unsupported operator '{op}' in procedural assertion")


def _label_comment(op: object, lang: str = "//") -> str:
    label = getattr(op, 'label', None)
    return f"{lang} Property: {label}\n" if label else ""


def convert(assert_module: assert_ir.AssertModule,
            signal_widths: Optional[Dict[str, int]] = None) -> str:
    """
    Convert an AssertModule to Yosys‑compatible SystemVerilog code.

    Args:
        assert_module: The unified assert module.
        signal_widths: Optional dictionary mapping signal names to their bit
                       widths.  If provided, multi‑bit signals are declared as
                       ``input logic [W-1:0] name``, otherwise they default to
                       single‑bit ``input logic name``.
    """
    mod_clock = assert_module.clock
    mod_reset = assert_module.reset

    signals = _collect_signals_robust(assert_module)

    lines = []
    lines.append("// Generated by InterScope – Yosys‑compatible procedural assertions")
    lines.append(f"// Design: {assert_module.name}")
    lines.append("")

    lines.append(f"module {assert_module.name} (")
    rst_sig = ""
    if mod_clock:
        lines.append(f"    input logic {mod_clock.clock_name},")
    if mod_reset:
        rst_cond = mod_reset.reset_condition.strip()
        rst_sig = rst_cond
        if rst_cond.startswith("(not ") and rst_cond.endswith(")"):
            rst_sig = rst_cond[5:-1].strip()
        lines.append(f"    input logic {rst_sig},")
    for sig in sorted(signals):
        if mod_clock and sig == mod_clock.clock_name:
            continue
        if mod_reset and sig == rst_sig:
            continue
        width = signal_widths.get(sig, 1) if signal_widths else 1
        if width > 1:
            lines.append(f"    input logic [{width-1}:0] {sig},")
        else:
            lines.append(f"    input logic {sig},")
    if lines[-1].endswith(","):
        lines[-1] = lines[-1][:-1]
    lines.append(");")
    lines.append("")

    # Collect all assertion conditions (with their labels)
    assertions = []

    # Assumptions (treated as assertions)
    for a in assert_module.assumptions:
        try:
            cond = _sva_expr(a.condition)
        except Exception as e:
            logger.warning("Skipping assumption '%s': %s", getattr(a, 'label', '?'), e)
            continue
        comment = _label_comment(a)
        assertions.append(f"{comment}assert ({cond});  // assume")

    # Always checks
    for c in assert_module.always_checks:
        try:
            cond = _sva_expr(c.condition)
        except Exception as e:
            logger.warning("Skipping always check '%s': %s", getattr(c, 'label', '?'), e)
            continue
        comment = _label_comment(c)
        assertions.append(f"{comment}assert ({cond});")

    # Temporal properties (only simple boolean operands supported)
    for p in assert_module.properties:
        if p.kind == "always" and p.operand:
            try:
                cond = _sva_expr(p.operand)
            except Exception as e:
                logger.warning("Skipping property '%s': %s", getattr(p, 'label', '?'), e)
                continue
            comment = _label_comment(p)
            assertions.append(f"{comment}assert ({cond});")
        else:
            logger.warning("Temporal property '%s' (kind=%s) not supported in procedural mode; skipping.",
                           getattr(p, 'label', '?'), p.kind)

    # Covers (treated as assertions for reachability)
    for cv in assert_module.covers:
        try:
            cond = _sva_expr(cv.condition)
        except Exception as e:
            logger.warning("Skipping cover '%s': %s", getattr(cv, 'label', '?'), e)
            continue
        comment = _label_comment(cv)
        assertions.append(f"{comment}assert ({cond});  // cover")

    # Build the procedural block
    if assertions:
        clock_name = mod_clock.clock_name if mod_clock else "clk"
        edge = mod_clock.edge if mod_clock else "posedge"

        lines.append(f"  always @({edge} {clock_name}) begin")
        if mod_reset:
            # The reset condition is an S‑expression – evaluate to a Boolean signal
            try:
                rst_expr = _sva_expr(mod_reset.reset_condition)
            except Exception:
                rst_expr = mod_reset.reset_condition  # fallback
            lines.append(f"    if ({rst_expr}) begin")
            lines.append(f"      // reset active – no assertion check")
            lines.append(f"    end else begin")
            for a in assertions:
                lines.append(f"      {a}")
            lines.append(f"    end")
        else:
            for a in assertions:
                lines.append(f"    {a}")
        lines.append(f"  end")

    lines.append("")
    lines.append("endmodule")

    return "\n".join(lines)


_KNOWN_OPERATORS = {
    "and", "or", "not", "eq", "neq", "gt", "lt", "gte", "lte", "le", "ge",
    "add", "sub", "mul", "div", "mod", "implies", "concat", "slice", "ite",
    "read", "write", "mem_read", "mem_write", "next", "prev", "rose", "fell",
    "stable"
}


def _collect_signals_robust(assert_module: assert_ir.AssertModule) -> Set[str]:
    signals: Set[str] = set()
    ops = (
        assert_module.assumptions +
        assert_module.always_checks +
        assert_module.properties +
        assert_module.covers
    )
    for op in ops:
        for attr in ("condition", "operand", "left", "right"):
            expr_str = getattr(op, attr, None)
            if expr_str:
                try:
                    parsed = parse_sexpr(expr_str)
                    _collect_from_parsed(parsed, signals)
                except ExprError:
                    _collect_fallback(expr_str, signals)
    return signals


def _collect_from_parsed(expr, signals):
    if isinstance(expr, (int, bool)):
        return
    if isinstance(expr, str):
        if expr not in _KNOWN_OPERATORS:
            signals.add(expr)
        return
    if isinstance(expr, list):
        for child in expr:
            _collect_from_parsed(child, signals)


def _collect_fallback(expr_str, signals):
    tokens = expr_str.replace('(', ' ').replace(')', ' ').split()
    for tok in tokens:
        if tok not in _KNOWN_OPERATORS and not tok.isdigit():
            signals.add(tok)
