# src/specir/verification/perf/perf_analyzer.py
#
# Structural analysis of a Coq proof obligation for PERF.
# Extracts information about step constructors, nested conditionals,
# duplicated sub‑expressions, and definitional properties to guide
# proof search strategies.

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from specir.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class ObligationAnalysis:
    """Result of analysing a proof obligation and its Coq environment.

    All fields are populated by ``PERFAnalyzer.analyze()`` and are used
    by the PERF engine to steer proof search, by the template generators
    to select appropriate proof sketches, and by the prompt builders to
    inject structural hints.

    Attributes:
        num_step_constructors: Number of ``step`` constructors (rules).
        step_constructor_names: Names of the ``step`` constructors
            (e.g. ``['step_load_inputs', 'step_execute']``).  These names
            are extracted verbatim from the Coq source and can be used to
            build precise inversion / case‑split instructions.
        has_nested_ite: Whether any step constructor contains nested ``if``
            (i.e. deeply cascaded conditionals).
        max_ite_depth: Maximum depth of ``if`` nesting in any constructor.
        expression_size: Approximate size of the theorem statement (char count).
        suggests_rule_splitting: The design would likely benefit from
            splitting a monolithic rule into several smaller ones.
        suggests_lemma_introduction: Large duplicated sub‑expressions were
            detected; introducing a helper lemma could simplify the proof.
        duplicated_subexpressions: Human‑readable descriptions of the
            duplicated patterns (if any).
        is_definitional: True if the property is definitionally true,
            i.e. of the form ``reg1 = (reg2 =? 0)`` (or similar) so that
            it can be proved trivially by case analysis and reflexivity.
    """

    num_step_constructors: int = 0
    step_constructor_names: List[str] = field(default_factory=list)
    has_nested_ite: bool = False
    max_ite_depth: int = 0
    expression_size: int = 0
    suggests_rule_splitting: bool = False
    suggests_lemma_introduction: bool = False
    duplicated_subexpressions: List[str] = field(default_factory=list)
    is_definitional: bool = False


class PERFAnalyzer:
    """Analyses a Coq file to extract structural hints for PERF."""

    # Patterns used to parse the generated Coq code
    _STEP_INDUCTIVE_RE = re.compile(
        r"Inductive\s+step\s*:.*?:=\s*(.*?)\.",
        re.DOTALL,
    )
    _CONSTRUCTOR_RE = re.compile(r"\|\s*step_(\w+)\s*:", re.DOTALL)
    _THEOREM_RE = re.compile(
        r"Theorem\s+(\w+)\s*:\s*(.*?)\.",
        re.DOTALL,
    )

    # Pattern for definitional properties:
    #   any register name (ending with _reg) equals Nat.eqb of another register with 0
    _DEFINITIONAL_RE = re.compile(
        r"(\w+_reg)\s+\w+\s*=\s*\(\s*Nat\.eqb\s+\(\s*(\w+_reg)\s+\w+\s*\)\s+0\s*\)"
    )

    def analyze(
        self,
        coq_file: Path,
        theorem_name: str,
    ) -> ObligationAnalysis:
        """Run the analysis on a Coq file.

        Args:
            coq_file: Path to the ``.v`` file generated by ``spec_to_koika``.
            theorem_name: Name of the theorem to analyse
                (e.g. ``zero_flag_correct_proved``).

        Returns:
            An ``ObligationAnalysis`` populated with the extracted metrics.
        """
        try:
            content = coq_file.read_text(encoding="utf-8")
        except Exception as e:
            logger.error("Failed to read Coq file %s: %s", coq_file, e)
            return ObligationAnalysis()

        # 1. Count step constructors and extract their names
        num_ctors, ctor_names, ctor_bodies = self._extract_step_constructors(content)

        # 2. Analyse nested conditionals inside the constructors
        max_depth = 0
        has_nested = False
        for body in ctor_bodies:
            depth = self._max_if_depth(body)
            if depth > max_depth:
                max_depth = depth
            if depth > 1:
                has_nested = True

        # 3. Find the theorem statement
        _, theorem_stmt = self._find_theorem(content, theorem_name)
        expr_size = len(theorem_stmt) if theorem_stmt else 0

        # 4. Detect duplicated large sub‑expressions
        duplicates = self._find_duplicated_subexprs(content, ctor_bodies, theorem_stmt)

        # 5. Heuristics
        suggests_split = (
            num_ctors == 1
            and max_depth >= 3
            and "step_execute" in content
        )
        suggests_lemma = len(duplicates) > 0

        # 6. Definitional property detection
        is_def = self._is_definitional(theorem_stmt) if theorem_stmt else False

        analysis = ObligationAnalysis(
            num_step_constructors=num_ctors,
            step_constructor_names=ctor_names,
            has_nested_ite=has_nested,
            max_ite_depth=max_depth,
            expression_size=expr_size,
            suggests_rule_splitting=suggests_split,
            suggests_lemma_introduction=suggests_lemma,
            duplicated_subexpressions=duplicates,
            is_definitional=is_def,
        )

        logger.debug(
            "Obligation analysis for '%s': %s",
            theorem_name,
            analysis,
        )
        return analysis

    def _extract_step_constructors(
        self, content: str
    ) -> Tuple[int, List[str], List[str]]:
        """Return the number of step constructors, their names,
        and a list of their bodies."""
        match = self._STEP_INDUCTIVE_RE.search(content)
        if not match:
            logger.warning("Could not locate 'Inductive step' definition.")
            return 0, [], []

        block = match.group(1)
        names = self._CONSTRUCTOR_RE.findall(block)
        if not names:
            return 0, [], []

        bodies: List[str] = []
        parts = re.split(r"\n\s*\| step_", block)
        for part in parts:
            stripped = part.strip()
            if stripped.startswith("step_"):
                colon_pos = stripped.find(":")
                if colon_pos != -1:
                    body = stripped[colon_pos + 1 :].strip()
                    bodies.append(body)
        if not parts[0].startswith("|"):
            first_body = parts[0].strip()
            if first_body.startswith("step_"):
                colon_pos = first_body.find(":")
                if colon_pos != -1:
                    first_body = first_body[colon_pos + 1 :].strip()
            bodies.insert(0, first_body)

        full_names = [f"step_{name}" for name in names]
        return len(names), full_names, bodies

    def _max_if_depth(self, body: str) -> int:
        """Compute the maximum nesting depth of ``if ... then ... else``."""
        depth = 0
        max_depth = 0
        clean = re.sub(r"\(\*.*?\*\)", "", body, flags=re.DOTALL)
        tokens = re.findall(r"\bif\b|\bthen\b|\belse\b", clean)
        for tok in tokens:
            if tok == "if":
                depth += 1
                max_depth = max(max_depth, depth)
        return max_depth

    def _find_theorem(
        self, content: str, theorem_name: str
    ) -> Tuple[Optional[str], Optional[str]]:
        """Return the full theorem statement for *theorem_name*."""
        for match in self._THEOREM_RE.finditer(content):
            name = match.group(1)
            if name == theorem_name:
                return name, match.group(2).strip()
        logger.warning("Theorem '%s' not found in file.", theorem_name)
        return None, None

    def _find_duplicated_subexprs(
        self,
        content: str,
        ctor_bodies: List[str],
        theorem_stmt: Optional[str],
    ) -> List[str]:
        """Detect large duplicated sub‑expressions within the step constructors."""
        duplicates: List[str] = []
        for body in ctor_bodies:
            record_match = re.search(r"\{\|.*?\|\}", body, re.DOTALL)
            if not record_match:
                continue
            record = record_match.group(0)
            result_reg_expr = self._extract_field(record, "result_reg")
            zero_reg_expr = self._extract_field(record, "zero_reg")
            if result_reg_expr and zero_reg_expr:
                if self._similar(result_reg_expr, zero_reg_expr):
                    duplicates.append(
                        "zero_reg computation duplicates result_reg expression; "
                        "introducing a lemma for result_reg could simplify the proof."
                    )
                overflow_reg_expr = self._extract_field(record, "overflow_reg")
                if overflow_reg_expr and result_reg_expr:
                    if self._similar(overflow_reg_expr[:100], result_reg_expr[:100]):
                        duplicates.append(
                            "overflow_reg and result_reg share common sub‑expressions; "
                            "helper lemmas may reduce complexity."
                        )
        return duplicates

    def _extract_field(self, record: str, field: str) -> Optional[str]:
        """Extract the right‑hand side of a record field assignment."""
        pattern = rf"{field}\s*:=\s*(.*?);"
        match = re.search(pattern, record, re.DOTALL)
        if match:
            return match.group(1).strip()
        return None

    def _similar(self, a: str, b: str, threshold: float = 0.8) -> bool:
        """Heuristic: check if two expressions are similar based on token overlap."""
        tokens_a = set(re.findall(r"\w+", a))
        tokens_b = set(re.findall(r"\w+", b))
        if not tokens_a or not tokens_b:
            return False
        intersection = tokens_a.intersection(tokens_b)
        union = tokens_a.union(tokens_b)
        jaccard = len(intersection) / len(union)
        return jaccard > threshold

    def _is_definitional(self, theorem_stmt: str) -> bool:
        """
        Check if the theorem statement describes a definitional property,
        e.g. ``zero_reg s = (Nat.eqb (result_reg s) 0)``.
        This pattern matches any register name ending with ``_reg`` on the
        left‑hand side and a ``Nat.eqb`` comparison of another ``_reg``
        register with zero on the right.
        """
        return bool(self._DEFINITIONAL_RE.search(theorem_stmt))
